<?php
/**
 * EventTypesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Convoy\Client\ApiException;
use Convoy\Client\Configuration;
use Convoy\Client\FormDataProcessor;
use Convoy\Client\HeaderSelector;
use Convoy\Client\ObjectSerializer;

/**
 * EventTypesApi Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventTypesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createEventType' => [
            'application/json',
        ],
        'deprecateEventType' => [
            'application/json',
        ],
        'getEventTypes' => [
            'application/json',
        ],
        'importOpenApiSpec' => [
            'application/json',
        ],
        'updateEventType' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createEventType
     *
     * Create an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsCreateEventType $models_create_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response
     */
    public function createEventType($project_id, $models_create_event_type, string $contentType = self::contentTypes['createEventType'][0])
    {
        list($response) = $this->createEventTypeWithHttpInfo($project_id, $models_create_event_type, $contentType);
        return $response;
    }

    /**
     * Operation createEventTypeWithHttpInfo
     *
     * Create an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsCreateEventType $models_create_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createEventTypeWithHttpInfo($project_id, $models_create_event_type, string $contentType = self::contentTypes['createEventType'][0])
    {
        $request = $this->createEventTypeRequest($project_id, $models_create_event_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Convoy\Client\Model\CreateEventType201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createEventTypeAsync
     *
     * Create an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsCreateEventType $models_create_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEventTypeAsync($project_id, $models_create_event_type, string $contentType = self::contentTypes['createEventType'][0])
    {
        return $this->createEventTypeAsyncWithHttpInfo($project_id, $models_create_event_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createEventTypeAsyncWithHttpInfo
     *
     * Create an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsCreateEventType $models_create_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createEventTypeAsyncWithHttpInfo($project_id, $models_create_event_type, string $contentType = self::contentTypes['createEventType'][0])
    {
        $returnType = '\Convoy\Client\Model\CreateEventType201Response';
        $request = $this->createEventTypeRequest($project_id, $models_create_event_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createEventType'
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsCreateEventType $models_create_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createEventTypeRequest($project_id, $models_create_event_type, string $contentType = self::contentTypes['createEventType'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling createEventType'
            );
        }

        // verify the required parameter 'models_create_event_type' is set
        if ($models_create_event_type === null || (is_array($models_create_event_type) && count($models_create_event_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $models_create_event_type when calling createEventType'
            );
        }


        $resourcePath = '/v1/projects/{projectID}/event-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{projectID}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($models_create_event_type)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($models_create_event_type));
            } else {
                $httpBody = $models_create_event_type;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deprecateEventType
     *
     * Deprecates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deprecateEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response
     */
    public function deprecateEventType($project_id, $event_type_id, string $contentType = self::contentTypes['deprecateEventType'][0])
    {
        list($response) = $this->deprecateEventTypeWithHttpInfo($project_id, $event_type_id, $contentType);
        return $response;
    }

    /**
     * Operation deprecateEventTypeWithHttpInfo
     *
     * Deprecates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deprecateEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deprecateEventTypeWithHttpInfo($project_id, $event_type_id, string $contentType = self::contentTypes['deprecateEventType'][0])
    {
        $request = $this->deprecateEventTypeRequest($project_id, $event_type_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Convoy\Client\Model\CreateEventType201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deprecateEventTypeAsync
     *
     * Deprecates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deprecateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deprecateEventTypeAsync($project_id, $event_type_id, string $contentType = self::contentTypes['deprecateEventType'][0])
    {
        return $this->deprecateEventTypeAsyncWithHttpInfo($project_id, $event_type_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deprecateEventTypeAsyncWithHttpInfo
     *
     * Deprecates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deprecateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deprecateEventTypeAsyncWithHttpInfo($project_id, $event_type_id, string $contentType = self::contentTypes['deprecateEventType'][0])
    {
        $returnType = '\Convoy\Client\Model\CreateEventType201Response';
        $request = $this->deprecateEventTypeRequest($project_id, $event_type_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deprecateEventType'
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deprecateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deprecateEventTypeRequest($project_id, $event_type_id, string $contentType = self::contentTypes['deprecateEventType'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling deprecateEventType'
            );
        }

        // verify the required parameter 'event_type_id' is set
        if ($event_type_id === null || (is_array($event_type_id) && count($event_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_id when calling deprecateEventType'
            );
        }


        $resourcePath = '/v1/projects/{projectID}/event-types/{eventTypeId}/deprecate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{projectID}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($event_type_id !== null) {
            $resourcePath = str_replace(
                '{eventTypeId}',
                ObjectSerializer::toPathValue($event_type_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEventTypes
     *
     * Retrieves a project&#39;s event types
     *
     * @param  string $project_id Project ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventTypes'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Convoy\Client\Model\GetEventTypes200Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response
     */
    public function getEventTypes($project_id, string $contentType = self::contentTypes['getEventTypes'][0])
    {
        list($response) = $this->getEventTypesWithHttpInfo($project_id, $contentType);
        return $response;
    }

    /**
     * Operation getEventTypesWithHttpInfo
     *
     * Retrieves a project&#39;s event types
     *
     * @param  string $project_id Project ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventTypes'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Convoy\Client\Model\GetEventTypes200Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEventTypesWithHttpInfo($project_id, string $contentType = self::contentTypes['getEventTypes'][0])
    {
        $request = $this->getEventTypesRequest($project_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetEventTypes200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Convoy\Client\Model\GetEventTypes200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetEventTypes200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getEventTypesAsync
     *
     * Retrieves a project&#39;s event types
     *
     * @param  string $project_id Project ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventTypesAsync($project_id, string $contentType = self::contentTypes['getEventTypes'][0])
    {
        return $this->getEventTypesAsyncWithHttpInfo($project_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEventTypesAsyncWithHttpInfo
     *
     * Retrieves a project&#39;s event types
     *
     * @param  string $project_id Project ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEventTypesAsyncWithHttpInfo($project_id, string $contentType = self::contentTypes['getEventTypes'][0])
    {
        $returnType = '\Convoy\Client\Model\GetEventTypes200Response';
        $request = $this->getEventTypesRequest($project_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEventTypes'
     *
     * @param  string $project_id Project ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getEventTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getEventTypesRequest($project_id, string $contentType = self::contentTypes['getEventTypes'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getEventTypes'
            );
        }


        $resourcePath = '/v1/projects/{projectID}/event-types';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{projectID}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation importOpenApiSpec
     *
     * Import event types from OpenAPI spec
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsImportOpenAPISpec $models_import_open_api_spec OpenAPI specification (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importOpenApiSpec'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Convoy\Client\Model\GetEventTypes200Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response
     */
    public function importOpenApiSpec($project_id, $models_import_open_api_spec, string $contentType = self::contentTypes['importOpenApiSpec'][0])
    {
        list($response) = $this->importOpenApiSpecWithHttpInfo($project_id, $models_import_open_api_spec, $contentType);
        return $response;
    }

    /**
     * Operation importOpenApiSpecWithHttpInfo
     *
     * Import event types from OpenAPI spec
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsImportOpenAPISpec $models_import_open_api_spec OpenAPI specification (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importOpenApiSpec'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Convoy\Client\Model\GetEventTypes200Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function importOpenApiSpecWithHttpInfo($project_id, $models_import_open_api_spec, string $contentType = self::contentTypes['importOpenApiSpec'][0])
    {
        $request = $this->importOpenApiSpecRequest($project_id, $models_import_open_api_spec, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetEventTypes200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Convoy\Client\Model\GetEventTypes200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetEventTypes200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation importOpenApiSpecAsync
     *
     * Import event types from OpenAPI spec
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsImportOpenAPISpec $models_import_open_api_spec OpenAPI specification (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importOpenApiSpec'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importOpenApiSpecAsync($project_id, $models_import_open_api_spec, string $contentType = self::contentTypes['importOpenApiSpec'][0])
    {
        return $this->importOpenApiSpecAsyncWithHttpInfo($project_id, $models_import_open_api_spec, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation importOpenApiSpecAsyncWithHttpInfo
     *
     * Import event types from OpenAPI spec
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsImportOpenAPISpec $models_import_open_api_spec OpenAPI specification (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importOpenApiSpec'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importOpenApiSpecAsyncWithHttpInfo($project_id, $models_import_open_api_spec, string $contentType = self::contentTypes['importOpenApiSpec'][0])
    {
        $returnType = '\Convoy\Client\Model\GetEventTypes200Response';
        $request = $this->importOpenApiSpecRequest($project_id, $models_import_open_api_spec, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'importOpenApiSpec'
     *
     * @param  string $project_id Project ID (required)
     * @param  \Convoy\Client\Model\ModelsImportOpenAPISpec $models_import_open_api_spec OpenAPI specification (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['importOpenApiSpec'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function importOpenApiSpecRequest($project_id, $models_import_open_api_spec, string $contentType = self::contentTypes['importOpenApiSpec'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling importOpenApiSpec'
            );
        }

        // verify the required parameter 'models_import_open_api_spec' is set
        if ($models_import_open_api_spec === null || (is_array($models_import_open_api_spec) && count($models_import_open_api_spec) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $models_import_open_api_spec when calling importOpenApiSpec'
            );
        }


        $resourcePath = '/v1/projects/{projectID}/event-types/import';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{projectID}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($models_import_open_api_spec)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($models_import_open_api_spec));
            } else {
                $httpBody = $models_import_open_api_spec;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateEventType
     *
     * Updates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  \Convoy\Client\Model\ModelsUpdateEventType $models_update_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response
     */
    public function updateEventType($project_id, $event_type_id, $models_update_event_type, string $contentType = self::contentTypes['updateEventType'][0])
    {
        list($response) = $this->updateEventTypeWithHttpInfo($project_id, $event_type_id, $models_update_event_type, $contentType);
        return $response;
    }

    /**
     * Operation updateEventTypeWithHttpInfo
     *
     * Updates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  \Convoy\Client\Model\ModelsUpdateEventType $models_update_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEventType'] to see the possible values for this operation
     *
     * @throws \Convoy\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Convoy\Client\Model\CreateEventType201Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response|\Convoy\Client\Model\GetProjects400Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateEventTypeWithHttpInfo($project_id, $event_type_id, $models_update_event_type, string $contentType = self::contentTypes['updateEventType'][0])
    {
        $request = $this->updateEventTypeRequest($project_id, $event_type_id, $models_update_event_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Convoy\Client\Model\GetProjects400Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Convoy\Client\Model\CreateEventType201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\CreateEventType201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Convoy\Client\Model\GetProjects400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateEventTypeAsync
     *
     * Updates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  \Convoy\Client\Model\ModelsUpdateEventType $models_update_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEventTypeAsync($project_id, $event_type_id, $models_update_event_type, string $contentType = self::contentTypes['updateEventType'][0])
    {
        return $this->updateEventTypeAsyncWithHttpInfo($project_id, $event_type_id, $models_update_event_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateEventTypeAsyncWithHttpInfo
     *
     * Updates an event type
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  \Convoy\Client\Model\ModelsUpdateEventType $models_update_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateEventTypeAsyncWithHttpInfo($project_id, $event_type_id, $models_update_event_type, string $contentType = self::contentTypes['updateEventType'][0])
    {
        $returnType = '\Convoy\Client\Model\CreateEventType201Response';
        $request = $this->updateEventTypeRequest($project_id, $event_type_id, $models_update_event_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateEventType'
     *
     * @param  string $project_id Project ID (required)
     * @param  string $event_type_id Event Type ID (required)
     * @param  \Convoy\Client\Model\ModelsUpdateEventType $models_update_event_type Event Type Details (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateEventType'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateEventTypeRequest($project_id, $event_type_id, $models_update_event_type, string $contentType = self::contentTypes['updateEventType'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling updateEventType'
            );
        }

        // verify the required parameter 'event_type_id' is set
        if ($event_type_id === null || (is_array($event_type_id) && count($event_type_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_type_id when calling updateEventType'
            );
        }

        // verify the required parameter 'models_update_event_type' is set
        if ($models_update_event_type === null || (is_array($models_update_event_type) && count($models_update_event_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $models_update_event_type when calling updateEventType'
            );
        }


        $resourcePath = '/v1/projects/{projectID}/event-types/{eventTypeId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{projectID}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }
        // path params
        if ($event_type_id !== null) {
            $resourcePath = str_replace(
                '{eventTypeId}',
                ObjectSerializer::toPathValue($event_type_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($models_update_event_type)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($models_update_event_type));
            } else {
                $httpBody = $models_update_event_type;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
