<?php
/**
 * AuthRoleType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;
use \Convoy\Client\ObjectSerializer;

/**
 * AuthRoleType Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuthRoleType
{
    /**
     * Possible values of this enum
     */
    /**
     * Instance level - can manage all orgs and projects
     */
    public const ROLE_INSTANCE_ADMIN = 'instance_admin';

    /**
     * Organisation level - can manage org and all projects
     */
    public const ROLE_ORGANISATION_ADMIN = 'organisation_admin';

    /**
     * Organisation level - can manage billing only TODO:
     */
    public const ROLE_BILLING_ADMIN = 'billing_admin';

    /**
     * Project level - can manage project settings and users
     */
    public const ROLE_PROJECT_ADMIN = 'project_admin';

    /**
     * Project level - can view project data only
     */
    public const ROLE_PROJECT_VIEWER = 'project_viewer';

    /**
     * 
     */
    public const ROLE_API = 'api';

    public const EMPTY = '';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ROLE_INSTANCE_ADMIN,
            self::ROLE_ORGANISATION_ADMIN,
            self::ROLE_BILLING_ADMIN,
            self::ROLE_PROJECT_ADMIN,
            self::ROLE_PROJECT_VIEWER,
            self::ROLE_API,
            self::EMPTY
        ];
    }
}


