<?php
/**
 * DatastoreEndpoint
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * DatastoreEndpoint Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DatastoreEndpoint implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'datastore.Endpoint';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'advanced_signatures' => 'bool',
        'authentication' => '\Convoy\Client\Model\DatastoreEndpointAuthentication',
        'cb_state' => 'string',
        'content_type' => 'string',
        'created_at' => 'string',
        'deleted_at' => 'string',
        'description' => 'string',
        'events' => 'int',
        'failure_count' => 'int',
        'failure_rate' => 'float',
        'http_timeout' => 'int',
        'mtls_client_cert' => '\Convoy\Client\Model\DatastoreMtlsClientCert',
        'name' => 'string',
        'owner_id' => 'string',
        'period_failure_rate' => 'float',
        'project_id' => 'string',
        'rate_limit' => 'int',
        'rate_limit_duration' => 'int',
        'retry_count' => 'int',
        'secrets' => '\Convoy\Client\Model\DatastoreSecret[]',
        'slack_webhook_url' => 'string',
        'status' => '\Convoy\Client\Model\DatastoreEndpointStatus',
        'success_count' => 'int',
        'support_email' => 'string',
        'uid' => 'string',
        'updated_at' => 'string',
        'url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'advanced_signatures' => null,
        'authentication' => null,
        'cb_state' => null,
        'content_type' => null,
        'created_at' => null,
        'deleted_at' => null,
        'description' => null,
        'events' => null,
        'failure_count' => null,
        'failure_rate' => null,
        'http_timeout' => null,
        'mtls_client_cert' => null,
        'name' => null,
        'owner_id' => null,
        'period_failure_rate' => null,
        'project_id' => null,
        'rate_limit' => null,
        'rate_limit_duration' => null,
        'retry_count' => null,
        'secrets' => null,
        'slack_webhook_url' => null,
        'status' => null,
        'success_count' => null,
        'support_email' => null,
        'uid' => null,
        'updated_at' => null,
        'url' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'advanced_signatures' => false,
        'authentication' => false,
        'cb_state' => false,
        'content_type' => false,
        'created_at' => false,
        'deleted_at' => false,
        'description' => false,
        'events' => false,
        'failure_count' => false,
        'failure_rate' => false,
        'http_timeout' => false,
        'mtls_client_cert' => false,
        'name' => false,
        'owner_id' => false,
        'period_failure_rate' => false,
        'project_id' => false,
        'rate_limit' => false,
        'rate_limit_duration' => false,
        'retry_count' => false,
        'secrets' => false,
        'slack_webhook_url' => false,
        'status' => false,
        'success_count' => false,
        'support_email' => false,
        'uid' => false,
        'updated_at' => false,
        'url' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'advanced_signatures' => 'advanced_signatures',
        'authentication' => 'authentication',
        'cb_state' => 'cb_state',
        'content_type' => 'content_type',
        'created_at' => 'created_at',
        'deleted_at' => 'deleted_at',
        'description' => 'description',
        'events' => 'events',
        'failure_count' => 'failure_count',
        'failure_rate' => 'failure_rate',
        'http_timeout' => 'http_timeout',
        'mtls_client_cert' => 'mtls_client_cert',
        'name' => 'name',
        'owner_id' => 'owner_id',
        'period_failure_rate' => 'period_failure_rate',
        'project_id' => 'project_id',
        'rate_limit' => 'rate_limit',
        'rate_limit_duration' => 'rate_limit_duration',
        'retry_count' => 'retry_count',
        'secrets' => 'secrets',
        'slack_webhook_url' => 'slack_webhook_url',
        'status' => 'status',
        'success_count' => 'success_count',
        'support_email' => 'support_email',
        'uid' => 'uid',
        'updated_at' => 'updated_at',
        'url' => 'url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'advanced_signatures' => 'setAdvancedSignatures',
        'authentication' => 'setAuthentication',
        'cb_state' => 'setCbState',
        'content_type' => 'setContentType',
        'created_at' => 'setCreatedAt',
        'deleted_at' => 'setDeletedAt',
        'description' => 'setDescription',
        'events' => 'setEvents',
        'failure_count' => 'setFailureCount',
        'failure_rate' => 'setFailureRate',
        'http_timeout' => 'setHttpTimeout',
        'mtls_client_cert' => 'setMtlsClientCert',
        'name' => 'setName',
        'owner_id' => 'setOwnerId',
        'period_failure_rate' => 'setPeriodFailureRate',
        'project_id' => 'setProjectId',
        'rate_limit' => 'setRateLimit',
        'rate_limit_duration' => 'setRateLimitDuration',
        'retry_count' => 'setRetryCount',
        'secrets' => 'setSecrets',
        'slack_webhook_url' => 'setSlackWebhookUrl',
        'status' => 'setStatus',
        'success_count' => 'setSuccessCount',
        'support_email' => 'setSupportEmail',
        'uid' => 'setUid',
        'updated_at' => 'setUpdatedAt',
        'url' => 'setUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'advanced_signatures' => 'getAdvancedSignatures',
        'authentication' => 'getAuthentication',
        'cb_state' => 'getCbState',
        'content_type' => 'getContentType',
        'created_at' => 'getCreatedAt',
        'deleted_at' => 'getDeletedAt',
        'description' => 'getDescription',
        'events' => 'getEvents',
        'failure_count' => 'getFailureCount',
        'failure_rate' => 'getFailureRate',
        'http_timeout' => 'getHttpTimeout',
        'mtls_client_cert' => 'getMtlsClientCert',
        'name' => 'getName',
        'owner_id' => 'getOwnerId',
        'period_failure_rate' => 'getPeriodFailureRate',
        'project_id' => 'getProjectId',
        'rate_limit' => 'getRateLimit',
        'rate_limit_duration' => 'getRateLimitDuration',
        'retry_count' => 'getRetryCount',
        'secrets' => 'getSecrets',
        'slack_webhook_url' => 'getSlackWebhookUrl',
        'status' => 'getStatus',
        'success_count' => 'getSuccessCount',
        'support_email' => 'getSupportEmail',
        'uid' => 'getUid',
        'updated_at' => 'getUpdatedAt',
        'url' => 'getUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('advanced_signatures', $data ?? [], null);
        $this->setIfExists('authentication', $data ?? [], null);
        $this->setIfExists('cb_state', $data ?? [], null);
        $this->setIfExists('content_type', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
        $this->setIfExists('failure_count', $data ?? [], null);
        $this->setIfExists('failure_rate', $data ?? [], null);
        $this->setIfExists('http_timeout', $data ?? [], null);
        $this->setIfExists('mtls_client_cert', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('owner_id', $data ?? [], null);
        $this->setIfExists('period_failure_rate', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('rate_limit', $data ?? [], null);
        $this->setIfExists('rate_limit_duration', $data ?? [], null);
        $this->setIfExists('retry_count', $data ?? [], null);
        $this->setIfExists('secrets', $data ?? [], null);
        $this->setIfExists('slack_webhook_url', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('success_count', $data ?? [], null);
        $this->setIfExists('support_email', $data ?? [], null);
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets advanced_signatures
     *
     * @return bool|null
     */
    public function getAdvancedSignatures()
    {
        return $this->container['advanced_signatures'];
    }

    /**
     * Sets advanced_signatures
     *
     * @param bool|null $advanced_signatures advanced_signatures
     *
     * @return self
     */
    public function setAdvancedSignatures($advanced_signatures)
    {
        if (is_null($advanced_signatures)) {
            throw new \InvalidArgumentException('non-nullable advanced_signatures cannot be null');
        }
        $this->container['advanced_signatures'] = $advanced_signatures;

        return $this;
    }

    /**
     * Gets authentication
     *
     * @return \Convoy\Client\Model\DatastoreEndpointAuthentication|null
     */
    public function getAuthentication()
    {
        return $this->container['authentication'];
    }

    /**
     * Sets authentication
     *
     * @param \Convoy\Client\Model\DatastoreEndpointAuthentication|null $authentication authentication
     *
     * @return self
     */
    public function setAuthentication($authentication)
    {
        if (is_null($authentication)) {
            throw new \InvalidArgumentException('non-nullable authentication cannot be null');
        }
        $this->container['authentication'] = $authentication;

        return $this;
    }

    /**
     * Gets cb_state
     *
     * @return string|null
     */
    public function getCbState()
    {
        return $this->container['cb_state'];
    }

    /**
     * Sets cb_state
     *
     * @param string|null $cb_state CBState is the circuit breaker state (\"open\", \"half-open\", \"closed\") so the UI can reflect a tripped breaker on the endpoint status. Nil when CB is off/unlicensed or has no sample for this endpoint.
     *
     * @return self
     */
    public function setCbState($cb_state)
    {
        if (is_null($cb_state)) {
            throw new \InvalidArgumentException('non-nullable cb_state cannot be null');
        }
        $this->container['cb_state'] = $cb_state;

        return $this;
    }

    /**
     * Gets content_type
     *
     * @return string|null
     */
    public function getContentType()
    {
        return $this->container['content_type'];
    }

    /**
     * Sets content_type
     *
     * @param string|null $content_type content_type
     *
     * @return self
     */
    public function setContentType($content_type)
    {
        if (is_null($content_type)) {
            throw new \InvalidArgumentException('non-nullable content_type cannot be null');
        }
        $this->container['content_type'] = $content_type;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return string|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param string|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            throw new \InvalidArgumentException('non-nullable deleted_at cannot be null');
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets events
     *
     * @return int|null
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param int|null $events events
     *
     * @return self
     */
    public function setEvents($events)
    {
        if (is_null($events)) {
            throw new \InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets failure_count
     *
     * @return int|null
     */
    public function getFailureCount()
    {
        return $this->container['failure_count'];
    }

    /**
     * Sets failure_count
     *
     * @param int|null $failure_count failure_count
     *
     * @return self
     */
    public function setFailureCount($failure_count)
    {
        if (is_null($failure_count)) {
            throw new \InvalidArgumentException('non-nullable failure_count cannot be null');
        }
        $this->container['failure_count'] = $failure_count;

        return $this;
    }

    /**
     * Gets failure_rate
     *
     * @return float|null
     */
    public function getFailureRate()
    {
        return $this->container['failure_rate'];
    }

    /**
     * Sets failure_rate
     *
     * @param float|null $failure_rate FailureRate is the circuit breaker's rolling failure rate for this endpoint. It is a pointer so the API can return null when no rate was computed (circuit breaker feature off, or sampler not running), distinct from a genuine 0%.
     *
     * @return self
     */
    public function setFailureRate($failure_rate)
    {
        if (is_null($failure_rate)) {
            throw new \InvalidArgumentException('non-nullable failure_rate cannot be null');
        }
        $this->container['failure_rate'] = $failure_rate;

        return $this;
    }

    /**
     * Gets http_timeout
     *
     * @return int|null
     */
    public function getHttpTimeout()
    {
        return $this->container['http_timeout'];
    }

    /**
     * Sets http_timeout
     *
     * @param int|null $http_timeout http_timeout
     *
     * @return self
     */
    public function setHttpTimeout($http_timeout)
    {
        if (is_null($http_timeout)) {
            throw new \InvalidArgumentException('non-nullable http_timeout cannot be null');
        }
        $this->container['http_timeout'] = $http_timeout;

        return $this;
    }

    /**
     * Gets mtls_client_cert
     *
     * @return \Convoy\Client\Model\DatastoreMtlsClientCert|null
     */
    public function getMtlsClientCert()
    {
        return $this->container['mtls_client_cert'];
    }

    /**
     * Sets mtls_client_cert
     *
     * @param \Convoy\Client\Model\DatastoreMtlsClientCert|null $mtls_client_cert mTLS client certificate configuration
     *
     * @return self
     */
    public function setMtlsClientCert($mtls_client_cert)
    {
        if (is_null($mtls_client_cert)) {
            throw new \InvalidArgumentException('non-nullable mtls_client_cert cannot be null');
        }
        $this->container['mtls_client_cert'] = $mtls_client_cert;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets owner_id
     *
     * @return string|null
     */
    public function getOwnerId()
    {
        return $this->container['owner_id'];
    }

    /**
     * Sets owner_id
     *
     * @param string|null $owner_id owner_id
     *
     * @return self
     */
    public function setOwnerId($owner_id)
    {
        if (is_null($owner_id)) {
            throw new \InvalidArgumentException('non-nullable owner_id cannot be null');
        }
        $this->container['owner_id'] = $owner_id;

        return $this;
    }

    /**
     * Gets period_failure_rate
     *
     * @return float|null
     */
    public function getPeriodFailureRate()
    {
        return $this->container['period_failure_rate'];
    }

    /**
     * Sets period_failure_rate
     *
     * @param float|null $period_failure_rate PeriodFailureRate is the period failure rate from event_deliveries, (Failure+Retry)/(Success+Failure+Retry). Retry counts as failed-so-far. Nil when the range has no counted deliveries; sibling counts are transient.
     *
     * @return self
     */
    public function setPeriodFailureRate($period_failure_rate)
    {
        if (is_null($period_failure_rate)) {
            throw new \InvalidArgumentException('non-nullable period_failure_rate cannot be null');
        }
        $this->container['period_failure_rate'] = $period_failure_rate;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets rate_limit
     *
     * @return int|null
     */
    public function getRateLimit()
    {
        return $this->container['rate_limit'];
    }

    /**
     * Sets rate_limit
     *
     * @param int|null $rate_limit rate_limit
     *
     * @return self
     */
    public function setRateLimit($rate_limit)
    {
        if (is_null($rate_limit)) {
            throw new \InvalidArgumentException('non-nullable rate_limit cannot be null');
        }
        $this->container['rate_limit'] = $rate_limit;

        return $this;
    }

    /**
     * Gets rate_limit_duration
     *
     * @return int|null
     */
    public function getRateLimitDuration()
    {
        return $this->container['rate_limit_duration'];
    }

    /**
     * Sets rate_limit_duration
     *
     * @param int|null $rate_limit_duration rate_limit_duration
     *
     * @return self
     */
    public function setRateLimitDuration($rate_limit_duration)
    {
        if (is_null($rate_limit_duration)) {
            throw new \InvalidArgumentException('non-nullable rate_limit_duration cannot be null');
        }
        $this->container['rate_limit_duration'] = $rate_limit_duration;

        return $this;
    }

    /**
     * Gets retry_count
     *
     * @return int|null
     */
    public function getRetryCount()
    {
        return $this->container['retry_count'];
    }

    /**
     * Sets retry_count
     *
     * @param int|null $retry_count retry_count
     *
     * @return self
     */
    public function setRetryCount($retry_count)
    {
        if (is_null($retry_count)) {
            throw new \InvalidArgumentException('non-nullable retry_count cannot be null');
        }
        $this->container['retry_count'] = $retry_count;

        return $this;
    }

    /**
     * Gets secrets
     *
     * @return \Convoy\Client\Model\DatastoreSecret[]|null
     */
    public function getSecrets()
    {
        return $this->container['secrets'];
    }

    /**
     * Sets secrets
     *
     * @param \Convoy\Client\Model\DatastoreSecret[]|null $secrets secrets
     *
     * @return self
     */
    public function setSecrets($secrets)
    {
        if (is_null($secrets)) {
            throw new \InvalidArgumentException('non-nullable secrets cannot be null');
        }
        $this->container['secrets'] = $secrets;

        return $this;
    }

    /**
     * Gets slack_webhook_url
     *
     * @return string|null
     */
    public function getSlackWebhookUrl()
    {
        return $this->container['slack_webhook_url'];
    }

    /**
     * Sets slack_webhook_url
     *
     * @param string|null $slack_webhook_url slack_webhook_url
     *
     * @return self
     */
    public function setSlackWebhookUrl($slack_webhook_url)
    {
        if (is_null($slack_webhook_url)) {
            throw new \InvalidArgumentException('non-nullable slack_webhook_url cannot be null');
        }
        $this->container['slack_webhook_url'] = $slack_webhook_url;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Convoy\Client\Model\DatastoreEndpointStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Convoy\Client\Model\DatastoreEndpointStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets success_count
     *
     * @return int|null
     */
    public function getSuccessCount()
    {
        return $this->container['success_count'];
    }

    /**
     * Sets success_count
     *
     * @param int|null $success_count success_count
     *
     * @return self
     */
    public function setSuccessCount($success_count)
    {
        if (is_null($success_count)) {
            throw new \InvalidArgumentException('non-nullable success_count cannot be null');
        }
        $this->container['success_count'] = $success_count;

        return $this;
    }

    /**
     * Gets support_email
     *
     * @return string|null
     */
    public function getSupportEmail()
    {
        return $this->container['support_email'];
    }

    /**
     * Sets support_email
     *
     * @param string|null $support_email support_email
     *
     * @return self
     */
    public function setSupportEmail($support_email)
    {
        if (is_null($support_email)) {
            throw new \InvalidArgumentException('non-nullable support_email cannot be null');
        }
        $this->container['support_email'] = $support_email;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return string|null
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string|null $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            throw new \InvalidArgumentException('non-nullable uid cannot be null');
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


