<?php
/**
 * DatastoreSource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * DatastoreSource Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DatastoreSource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'datastore.Source';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'body_function' => 'string',
        'created_at' => 'string',
        'custom_response' => '\Convoy\Client\Model\DatastoreCustomResponse',
        'deleted_at' => 'string',
        'event_type_location' => 'string',
        'forward_headers' => 'string[]',
        'header_function' => 'string',
        'idempotency_keys' => 'string[]',
        'is_disabled' => 'bool',
        'mask_id' => 'string',
        'name' => 'string',
        'project_id' => 'string',
        'provider' => '\Convoy\Client\Model\DatastoreSourceProvider',
        'provider_config' => '\Convoy\Client\Model\DatastoreProviderConfig',
        'pub_sub' => '\Convoy\Client\Model\DatastorePubSubConfig',
        'type' => '\Convoy\Client\Model\DatastoreSourceType',
        'uid' => 'string',
        'updated_at' => 'string',
        'url' => 'string',
        'verifier' => '\Convoy\Client\Model\DatastoreVerifierConfig'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'body_function' => null,
        'created_at' => null,
        'custom_response' => null,
        'deleted_at' => null,
        'event_type_location' => null,
        'forward_headers' => null,
        'header_function' => null,
        'idempotency_keys' => null,
        'is_disabled' => null,
        'mask_id' => null,
        'name' => null,
        'project_id' => null,
        'provider' => null,
        'provider_config' => null,
        'pub_sub' => null,
        'type' => null,
        'uid' => null,
        'updated_at' => null,
        'url' => null,
        'verifier' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'body_function' => true,
        'created_at' => false,
        'custom_response' => false,
        'deleted_at' => true,
        'event_type_location' => false,
        'forward_headers' => false,
        'header_function' => true,
        'idempotency_keys' => false,
        'is_disabled' => false,
        'mask_id' => false,
        'name' => false,
        'project_id' => false,
        'provider' => false,
        'provider_config' => true,
        'pub_sub' => true,
        'type' => false,
        'uid' => false,
        'updated_at' => false,
        'url' => false,
        'verifier' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'body_function' => 'body_function',
        'created_at' => 'created_at',
        'custom_response' => 'custom_response',
        'deleted_at' => 'deleted_at',
        'event_type_location' => 'event_type_location',
        'forward_headers' => 'forward_headers',
        'header_function' => 'header_function',
        'idempotency_keys' => 'idempotency_keys',
        'is_disabled' => 'is_disabled',
        'mask_id' => 'mask_id',
        'name' => 'name',
        'project_id' => 'project_id',
        'provider' => 'provider',
        'provider_config' => 'provider_config',
        'pub_sub' => 'pub_sub',
        'type' => 'type',
        'uid' => 'uid',
        'updated_at' => 'updated_at',
        'url' => 'url',
        'verifier' => 'verifier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'body_function' => 'setBodyFunction',
        'created_at' => 'setCreatedAt',
        'custom_response' => 'setCustomResponse',
        'deleted_at' => 'setDeletedAt',
        'event_type_location' => 'setEventTypeLocation',
        'forward_headers' => 'setForwardHeaders',
        'header_function' => 'setHeaderFunction',
        'idempotency_keys' => 'setIdempotencyKeys',
        'is_disabled' => 'setIsDisabled',
        'mask_id' => 'setMaskId',
        'name' => 'setName',
        'project_id' => 'setProjectId',
        'provider' => 'setProvider',
        'provider_config' => 'setProviderConfig',
        'pub_sub' => 'setPubSub',
        'type' => 'setType',
        'uid' => 'setUid',
        'updated_at' => 'setUpdatedAt',
        'url' => 'setUrl',
        'verifier' => 'setVerifier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'body_function' => 'getBodyFunction',
        'created_at' => 'getCreatedAt',
        'custom_response' => 'getCustomResponse',
        'deleted_at' => 'getDeletedAt',
        'event_type_location' => 'getEventTypeLocation',
        'forward_headers' => 'getForwardHeaders',
        'header_function' => 'getHeaderFunction',
        'idempotency_keys' => 'getIdempotencyKeys',
        'is_disabled' => 'getIsDisabled',
        'mask_id' => 'getMaskId',
        'name' => 'getName',
        'project_id' => 'getProjectId',
        'provider' => 'getProvider',
        'provider_config' => 'getProviderConfig',
        'pub_sub' => 'getPubSub',
        'type' => 'getType',
        'uid' => 'getUid',
        'updated_at' => 'getUpdatedAt',
        'url' => 'getUrl',
        'verifier' => 'getVerifier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('body_function', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('custom_response', $data ?? [], null);
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('event_type_location', $data ?? [], null);
        $this->setIfExists('forward_headers', $data ?? [], null);
        $this->setIfExists('header_function', $data ?? [], null);
        $this->setIfExists('idempotency_keys', $data ?? [], null);
        $this->setIfExists('is_disabled', $data ?? [], null);
        $this->setIfExists('mask_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('provider_config', $data ?? [], null);
        $this->setIfExists('pub_sub', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('uid', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('verifier', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets body_function
     *
     * @return string|null
     */
    public function getBodyFunction()
    {
        return $this->container['body_function'];
    }

    /**
     * Sets body_function
     *
     * @param string|null $body_function body_function
     *
     * @return self
     */
    public function setBodyFunction($body_function)
    {
        if (is_null($body_function)) {
            array_push($this->openAPINullablesSetToNull, 'body_function');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('body_function', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['body_function'] = $body_function;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets custom_response
     *
     * @return \Convoy\Client\Model\DatastoreCustomResponse|null
     */
    public function getCustomResponse()
    {
        return $this->container['custom_response'];
    }

    /**
     * Sets custom_response
     *
     * @param \Convoy\Client\Model\DatastoreCustomResponse|null $custom_response custom_response
     *
     * @return self
     */
    public function setCustomResponse($custom_response)
    {
        if (is_null($custom_response)) {
            throw new \InvalidArgumentException('non-nullable custom_response cannot be null');
        }
        $this->container['custom_response'] = $custom_response;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return string|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param string|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets event_type_location
     *
     * @return string|null
     */
    public function getEventTypeLocation()
    {
        return $this->container['event_type_location'];
    }

    /**
     * Sets event_type_location
     *
     * @param string|null $event_type_location event_type_location
     *
     * @return self
     */
    public function setEventTypeLocation($event_type_location)
    {
        if (is_null($event_type_location)) {
            throw new \InvalidArgumentException('non-nullable event_type_location cannot be null');
        }
        $this->container['event_type_location'] = $event_type_location;

        return $this;
    }

    /**
     * Gets forward_headers
     *
     * @return string[]|null
     */
    public function getForwardHeaders()
    {
        return $this->container['forward_headers'];
    }

    /**
     * Sets forward_headers
     *
     * @param string[]|null $forward_headers forward_headers
     *
     * @return self
     */
    public function setForwardHeaders($forward_headers)
    {
        if (is_null($forward_headers)) {
            throw new \InvalidArgumentException('non-nullable forward_headers cannot be null');
        }
        $this->container['forward_headers'] = $forward_headers;

        return $this;
    }

    /**
     * Gets header_function
     *
     * @return string|null
     */
    public function getHeaderFunction()
    {
        return $this->container['header_function'];
    }

    /**
     * Sets header_function
     *
     * @param string|null $header_function header_function
     *
     * @return self
     */
    public function setHeaderFunction($header_function)
    {
        if (is_null($header_function)) {
            array_push($this->openAPINullablesSetToNull, 'header_function');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_function', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_function'] = $header_function;

        return $this;
    }

    /**
     * Gets idempotency_keys
     *
     * @return string[]|null
     */
    public function getIdempotencyKeys()
    {
        return $this->container['idempotency_keys'];
    }

    /**
     * Sets idempotency_keys
     *
     * @param string[]|null $idempotency_keys idempotency_keys
     *
     * @return self
     */
    public function setIdempotencyKeys($idempotency_keys)
    {
        if (is_null($idempotency_keys)) {
            throw new \InvalidArgumentException('non-nullable idempotency_keys cannot be null');
        }
        $this->container['idempotency_keys'] = $idempotency_keys;

        return $this;
    }

    /**
     * Gets is_disabled
     *
     * @return bool|null
     */
    public function getIsDisabled()
    {
        return $this->container['is_disabled'];
    }

    /**
     * Sets is_disabled
     *
     * @param bool|null $is_disabled is_disabled
     *
     * @return self
     */
    public function setIsDisabled($is_disabled)
    {
        if (is_null($is_disabled)) {
            throw new \InvalidArgumentException('non-nullable is_disabled cannot be null');
        }
        $this->container['is_disabled'] = $is_disabled;

        return $this;
    }

    /**
     * Gets mask_id
     *
     * @return string|null
     */
    public function getMaskId()
    {
        return $this->container['mask_id'];
    }

    /**
     * Sets mask_id
     *
     * @param string|null $mask_id mask_id
     *
     * @return self
     */
    public function setMaskId($mask_id)
    {
        if (is_null($mask_id)) {
            throw new \InvalidArgumentException('non-nullable mask_id cannot be null');
        }
        $this->container['mask_id'] = $mask_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return \Convoy\Client\Model\DatastoreSourceProvider|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param \Convoy\Client\Model\DatastoreSourceProvider|null $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets provider_config
     *
     * @return \Convoy\Client\Model\DatastoreProviderConfig|null
     */
    public function getProviderConfig()
    {
        return $this->container['provider_config'];
    }

    /**
     * Sets provider_config
     *
     * @param \Convoy\Client\Model\DatastoreProviderConfig|null $provider_config provider_config
     *
     * @return self
     */
    public function setProviderConfig($provider_config)
    {
        if (is_null($provider_config)) {
            array_push($this->openAPINullablesSetToNull, 'provider_config');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider_config', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider_config'] = $provider_config;

        return $this;
    }

    /**
     * Gets pub_sub
     *
     * @return \Convoy\Client\Model\DatastorePubSubConfig|null
     */
    public function getPubSub()
    {
        return $this->container['pub_sub'];
    }

    /**
     * Sets pub_sub
     *
     * @param \Convoy\Client\Model\DatastorePubSubConfig|null $pub_sub pub_sub
     *
     * @return self
     */
    public function setPubSub($pub_sub)
    {
        if (is_null($pub_sub)) {
            array_push($this->openAPINullablesSetToNull, 'pub_sub');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pub_sub', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pub_sub'] = $pub_sub;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Convoy\Client\Model\DatastoreSourceType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Convoy\Client\Model\DatastoreSourceType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return string|null
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string|null $uid uid
     *
     * @return self
     */
    public function setUid($uid)
    {
        if (is_null($uid)) {
            throw new \InvalidArgumentException('non-nullable uid cannot be null');
        }
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets verifier
     *
     * @return \Convoy\Client\Model\DatastoreVerifierConfig|null
     */
    public function getVerifier()
    {
        return $this->container['verifier'];
    }

    /**
     * Sets verifier
     *
     * @param \Convoy\Client\Model\DatastoreVerifierConfig|null $verifier verifier
     *
     * @return self
     */
    public function setVerifier($verifier)
    {
        if (is_null($verifier)) {
            array_push($this->openAPINullablesSetToNull, 'verifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verifier'] = $verifier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


