<?php
/**
 * DatastoreCircuitBreakerConfiguration
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * DatastoreCircuitBreakerConfiguration Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DatastoreCircuitBreakerConfiguration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'datastore.CircuitBreakerConfiguration';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'consecutive_failure_threshold' => 'int',
        'error_timeout' => 'int',
        'failure_threshold' => 'int',
        'minimum_request_count' => 'int',
        'observability_window' => 'int',
        'sample_rate' => 'int',
        'success_threshold' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'consecutive_failure_threshold' => null,
        'error_timeout' => null,
        'failure_threshold' => null,
        'minimum_request_count' => null,
        'observability_window' => null,
        'sample_rate' => null,
        'success_threshold' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'consecutive_failure_threshold' => false,
        'error_timeout' => false,
        'failure_threshold' => false,
        'minimum_request_count' => false,
        'observability_window' => false,
        'sample_rate' => false,
        'success_threshold' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'consecutive_failure_threshold' => 'consecutive_failure_threshold',
        'error_timeout' => 'error_timeout',
        'failure_threshold' => 'failure_threshold',
        'minimum_request_count' => 'minimum_request_count',
        'observability_window' => 'observability_window',
        'sample_rate' => 'sample_rate',
        'success_threshold' => 'success_threshold'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'consecutive_failure_threshold' => 'setConsecutiveFailureThreshold',
        'error_timeout' => 'setErrorTimeout',
        'failure_threshold' => 'setFailureThreshold',
        'minimum_request_count' => 'setMinimumRequestCount',
        'observability_window' => 'setObservabilityWindow',
        'sample_rate' => 'setSampleRate',
        'success_threshold' => 'setSuccessThreshold'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'consecutive_failure_threshold' => 'getConsecutiveFailureThreshold',
        'error_timeout' => 'getErrorTimeout',
        'failure_threshold' => 'getFailureThreshold',
        'minimum_request_count' => 'getMinimumRequestCount',
        'observability_window' => 'getObservabilityWindow',
        'sample_rate' => 'getSampleRate',
        'success_threshold' => 'getSuccessThreshold'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('consecutive_failure_threshold', $data ?? [], null);
        $this->setIfExists('error_timeout', $data ?? [], null);
        $this->setIfExists('failure_threshold', $data ?? [], null);
        $this->setIfExists('minimum_request_count', $data ?? [], null);
        $this->setIfExists('observability_window', $data ?? [], null);
        $this->setIfExists('sample_rate', $data ?? [], null);
        $this->setIfExists('success_threshold', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets consecutive_failure_threshold
     *
     * @return int|null
     */
    public function getConsecutiveFailureThreshold()
    {
        return $this->container['consecutive_failure_threshold'];
    }

    /**
     * Sets consecutive_failure_threshold
     *
     * @param int|null $consecutive_failure_threshold consecutive_failure_threshold
     *
     * @return self
     */
    public function setConsecutiveFailureThreshold($consecutive_failure_threshold)
    {
        if (is_null($consecutive_failure_threshold)) {
            throw new \InvalidArgumentException('non-nullable consecutive_failure_threshold cannot be null');
        }
        $this->container['consecutive_failure_threshold'] = $consecutive_failure_threshold;

        return $this;
    }

    /**
     * Gets error_timeout
     *
     * @return int|null
     */
    public function getErrorTimeout()
    {
        return $this->container['error_timeout'];
    }

    /**
     * Sets error_timeout
     *
     * @param int|null $error_timeout error_timeout
     *
     * @return self
     */
    public function setErrorTimeout($error_timeout)
    {
        if (is_null($error_timeout)) {
            throw new \InvalidArgumentException('non-nullable error_timeout cannot be null');
        }
        $this->container['error_timeout'] = $error_timeout;

        return $this;
    }

    /**
     * Gets failure_threshold
     *
     * @return int|null
     */
    public function getFailureThreshold()
    {
        return $this->container['failure_threshold'];
    }

    /**
     * Sets failure_threshold
     *
     * @param int|null $failure_threshold failure_threshold
     *
     * @return self
     */
    public function setFailureThreshold($failure_threshold)
    {
        if (is_null($failure_threshold)) {
            throw new \InvalidArgumentException('non-nullable failure_threshold cannot be null');
        }
        $this->container['failure_threshold'] = $failure_threshold;

        return $this;
    }

    /**
     * Gets minimum_request_count
     *
     * @return int|null
     */
    public function getMinimumRequestCount()
    {
        return $this->container['minimum_request_count'];
    }

    /**
     * Sets minimum_request_count
     *
     * @param int|null $minimum_request_count minimum_request_count
     *
     * @return self
     */
    public function setMinimumRequestCount($minimum_request_count)
    {
        if (is_null($minimum_request_count)) {
            throw new \InvalidArgumentException('non-nullable minimum_request_count cannot be null');
        }
        $this->container['minimum_request_count'] = $minimum_request_count;

        return $this;
    }

    /**
     * Gets observability_window
     *
     * @return int|null
     */
    public function getObservabilityWindow()
    {
        return $this->container['observability_window'];
    }

    /**
     * Sets observability_window
     *
     * @param int|null $observability_window observability_window
     *
     * @return self
     */
    public function setObservabilityWindow($observability_window)
    {
        if (is_null($observability_window)) {
            throw new \InvalidArgumentException('non-nullable observability_window cannot be null');
        }
        $this->container['observability_window'] = $observability_window;

        return $this;
    }

    /**
     * Gets sample_rate
     *
     * @return int|null
     */
    public function getSampleRate()
    {
        return $this->container['sample_rate'];
    }

    /**
     * Sets sample_rate
     *
     * @param int|null $sample_rate sample_rate
     *
     * @return self
     */
    public function setSampleRate($sample_rate)
    {
        if (is_null($sample_rate)) {
            throw new \InvalidArgumentException('non-nullable sample_rate cannot be null');
        }
        $this->container['sample_rate'] = $sample_rate;

        return $this;
    }

    /**
     * Gets success_threshold
     *
     * @return int|null
     */
    public function getSuccessThreshold()
    {
        return $this->container['success_threshold'];
    }

    /**
     * Sets success_threshold
     *
     * @param int|null $success_threshold success_threshold
     *
     * @return self
     */
    public function setSuccessThreshold($success_threshold)
    {
        if (is_null($success_threshold)) {
            throw new \InvalidArgumentException('non-nullable success_threshold cannot be null');
        }
        $this->container['success_threshold'] = $success_threshold;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


