<?php
/**
 * DatastoreDeviceStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;
use \Convoy\Client\ObjectSerializer;

/**
 * DatastoreDeviceStatus Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatastoreDeviceStatus
{
    /**
     * Possible values of this enum
     */
    public const DEVICE_STATUS_OFFLINE = 'offline';

    public const DEVICE_STATUS_ONLINE = 'online';

    public const DEVICE_STATUS_DISABLED = 'disabled';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DEVICE_STATUS_OFFLINE,
            self::DEVICE_STATUS_ONLINE,
            self::DEVICE_STATUS_DISABLED
        ];
    }
}


