<?php
/**
 * ModelsCreateSource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * ModelsCreateSource Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelsCreateSource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'models.CreateSource';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'body_function' => 'string',
        'custom_response' => '\Convoy\Client\Model\ModelsCustomResponse',
        'event_type_location' => 'string',
        'header_function' => 'string',
        'idempotency_keys' => 'string[]',
        'name' => 'string',
        'provider' => '\Convoy\Client\Model\DatastoreSourceProvider',
        'pub_sub' => '\Convoy\Client\Model\ModelsPubSubConfig',
        'type' => '\Convoy\Client\Model\DatastoreSourceType',
        'verifier' => '\Convoy\Client\Model\ModelsVerifierConfig'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'body_function' => null,
        'custom_response' => null,
        'event_type_location' => null,
        'header_function' => null,
        'idempotency_keys' => null,
        'name' => null,
        'provider' => null,
        'pub_sub' => null,
        'type' => null,
        'verifier' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'body_function' => false,
        'custom_response' => false,
        'event_type_location' => false,
        'header_function' => false,
        'idempotency_keys' => false,
        'name' => false,
        'provider' => false,
        'pub_sub' => false,
        'type' => false,
        'verifier' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'body_function' => 'body_function',
        'custom_response' => 'custom_response',
        'event_type_location' => 'event_type_location',
        'header_function' => 'header_function',
        'idempotency_keys' => 'idempotency_keys',
        'name' => 'name',
        'provider' => 'provider',
        'pub_sub' => 'pub_sub',
        'type' => 'type',
        'verifier' => 'verifier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'body_function' => 'setBodyFunction',
        'custom_response' => 'setCustomResponse',
        'event_type_location' => 'setEventTypeLocation',
        'header_function' => 'setHeaderFunction',
        'idempotency_keys' => 'setIdempotencyKeys',
        'name' => 'setName',
        'provider' => 'setProvider',
        'pub_sub' => 'setPubSub',
        'type' => 'setType',
        'verifier' => 'setVerifier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'body_function' => 'getBodyFunction',
        'custom_response' => 'getCustomResponse',
        'event_type_location' => 'getEventTypeLocation',
        'header_function' => 'getHeaderFunction',
        'idempotency_keys' => 'getIdempotencyKeys',
        'name' => 'getName',
        'provider' => 'getProvider',
        'pub_sub' => 'getPubSub',
        'type' => 'getType',
        'verifier' => 'getVerifier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('body_function', $data ?? [], null);
        $this->setIfExists('custom_response', $data ?? [], null);
        $this->setIfExists('event_type_location', $data ?? [], null);
        $this->setIfExists('header_function', $data ?? [], null);
        $this->setIfExists('idempotency_keys', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('pub_sub', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('verifier', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets body_function
     *
     * @return string|null
     */
    public function getBodyFunction()
    {
        return $this->container['body_function'];
    }

    /**
     * Sets body_function
     *
     * @param string|null $body_function Function is a javascript function used to mutate the payload immediately after ingesting an event
     *
     * @return self
     */
    public function setBodyFunction($body_function)
    {
        if (is_null($body_function)) {
            throw new \InvalidArgumentException('non-nullable body_function cannot be null');
        }
        $this->container['body_function'] = $body_function;

        return $this;
    }

    /**
     * Gets custom_response
     *
     * @return \Convoy\Client\Model\ModelsCustomResponse|null
     */
    public function getCustomResponse()
    {
        return $this->container['custom_response'];
    }

    /**
     * Sets custom_response
     *
     * @param \Convoy\Client\Model\ModelsCustomResponse|null $custom_response Custom response is used to define a custom response for incoming webhooks project sources only.
     *
     * @return self
     */
    public function setCustomResponse($custom_response)
    {
        if (is_null($custom_response)) {
            throw new \InvalidArgumentException('non-nullable custom_response cannot be null');
        }
        $this->container['custom_response'] = $custom_response;

        return $this;
    }

    /**
     * Gets event_type_location
     *
     * @return string|null
     */
    public function getEventTypeLocation()
    {
        return $this->container['event_type_location'];
    }

    /**
     * Sets event_type_location
     *
     * @param string|null $event_type_location EventTypeLocation is used to specify where Convoy should read the event type from an incoming webhook request.
     *
     * @return self
     */
    public function setEventTypeLocation($event_type_location)
    {
        if (is_null($event_type_location)) {
            throw new \InvalidArgumentException('non-nullable event_type_location cannot be null');
        }
        $this->container['event_type_location'] = $event_type_location;

        return $this;
    }

    /**
     * Gets header_function
     *
     * @return string|null
     */
    public function getHeaderFunction()
    {
        return $this->container['header_function'];
    }

    /**
     * Sets header_function
     *
     * @param string|null $header_function Function is a javascript function used to mutate the headers immediately after ingesting an event
     *
     * @return self
     */
    public function setHeaderFunction($header_function)
    {
        if (is_null($header_function)) {
            throw new \InvalidArgumentException('non-nullable header_function cannot be null');
        }
        $this->container['header_function'] = $header_function;

        return $this;
    }

    /**
     * Gets idempotency_keys
     *
     * @return string[]|null
     */
    public function getIdempotencyKeys()
    {
        return $this->container['idempotency_keys'];
    }

    /**
     * Sets idempotency_keys
     *
     * @param string[]|null $idempotency_keys IdempotencyKeys are used to specify parts of a webhook request to uniquely identify the event in an incoming webhooks project.
     *
     * @return self
     */
    public function setIdempotencyKeys($idempotency_keys)
    {
        if (is_null($idempotency_keys)) {
            throw new \InvalidArgumentException('non-nullable idempotency_keys cannot be null');
        }
        $this->container['idempotency_keys'] = $idempotency_keys;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Source name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return \Convoy\Client\Model\DatastoreSourceProvider|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param \Convoy\Client\Model\DatastoreSourceProvider|null $provider Use this to specify one of our predefined source types.
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets pub_sub
     *
     * @return \Convoy\Client\Model\ModelsPubSubConfig|null
     */
    public function getPubSub()
    {
        return $this->container['pub_sub'];
    }

    /**
     * Sets pub_sub
     *
     * @param \Convoy\Client\Model\ModelsPubSubConfig|null $pub_sub PubSub are used to specify message broker sources for outgoing webhooks projects.
     *
     * @return self
     */
    public function setPubSub($pub_sub)
    {
        if (is_null($pub_sub)) {
            throw new \InvalidArgumentException('non-nullable pub_sub cannot be null');
        }
        $this->container['pub_sub'] = $pub_sub;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Convoy\Client\Model\DatastoreSourceType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Convoy\Client\Model\DatastoreSourceType|null $type Source Type.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets verifier
     *
     * @return \Convoy\Client\Model\ModelsVerifierConfig|null
     */
    public function getVerifier()
    {
        return $this->container['verifier'];
    }

    /**
     * Sets verifier
     *
     * @param \Convoy\Client\Model\ModelsVerifierConfig|null $verifier Verifiers are used to verify webhook events ingested in incoming webhooks projects. If set, type is required and match the verifier type object you choose.
     *
     * @return self
     */
    public function setVerifier($verifier)
    {
        if (is_null($verifier)) {
            throw new \InvalidArgumentException('non-nullable verifier cannot be null');
        }
        $this->container['verifier'] = $verifier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


