<?php
/**
 * ModelsCreateSubscription
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * ModelsCreateSubscription Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelsCreateSubscription implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'models.CreateSubscription';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'alert_config' => '\Convoy\Client\Model\ModelsAlertConfiguration',
        'app_id' => 'string',
        'delivery_mode' => '\Convoy\Client\Model\DatastoreDeliveryMode',
        'endpoint_id' => 'string',
        'filter_config' => '\Convoy\Client\Model\ModelsFilterConfiguration',
        'function' => 'string',
        'name' => 'string',
        'rate_limit_config' => '\Convoy\Client\Model\ModelsRateLimitConfiguration',
        'source_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'alert_config' => null,
        'app_id' => null,
        'delivery_mode' => null,
        'endpoint_id' => null,
        'filter_config' => null,
        'function' => null,
        'name' => null,
        'rate_limit_config' => null,
        'source_id' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'alert_config' => false,
        'app_id' => false,
        'delivery_mode' => false,
        'endpoint_id' => false,
        'filter_config' => false,
        'function' => false,
        'name' => false,
        'rate_limit_config' => false,
        'source_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'alert_config' => 'alert_config',
        'app_id' => 'app_id',
        'delivery_mode' => 'delivery_mode',
        'endpoint_id' => 'endpoint_id',
        'filter_config' => 'filter_config',
        'function' => 'function',
        'name' => 'name',
        'rate_limit_config' => 'rate_limit_config',
        'source_id' => 'source_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'alert_config' => 'setAlertConfig',
        'app_id' => 'setAppId',
        'delivery_mode' => 'setDeliveryMode',
        'endpoint_id' => 'setEndpointId',
        'filter_config' => 'setFilterConfig',
        'function' => 'setFunction',
        'name' => 'setName',
        'rate_limit_config' => 'setRateLimitConfig',
        'source_id' => 'setSourceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'alert_config' => 'getAlertConfig',
        'app_id' => 'getAppId',
        'delivery_mode' => 'getDeliveryMode',
        'endpoint_id' => 'getEndpointId',
        'filter_config' => 'getFilterConfig',
        'function' => 'getFunction',
        'name' => 'getName',
        'rate_limit_config' => 'getRateLimitConfig',
        'source_id' => 'getSourceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('alert_config', $data ?? [], null);
        $this->setIfExists('app_id', $data ?? [], null);
        $this->setIfExists('delivery_mode', $data ?? [], null);
        $this->setIfExists('endpoint_id', $data ?? [], null);
        $this->setIfExists('filter_config', $data ?? [], null);
        $this->setIfExists('function', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('rate_limit_config', $data ?? [], null);
        $this->setIfExists('source_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets alert_config
     *
     * @return \Convoy\Client\Model\ModelsAlertConfiguration|null
     */
    public function getAlertConfig()
    {
        return $this->container['alert_config'];
    }

    /**
     * Sets alert_config
     *
     * @param \Convoy\Client\Model\ModelsAlertConfiguration|null $alert_config Alert configuration
     *
     * @return self
     */
    public function setAlertConfig($alert_config)
    {
        if (is_null($alert_config)) {
            throw new \InvalidArgumentException('non-nullable alert_config cannot be null');
        }
        $this->container['alert_config'] = $alert_config;

        return $this;
    }

    /**
     * Gets app_id
     *
     * @return string|null
     */
    public function getAppId()
    {
        return $this->container['app_id'];
    }

    /**
     * Sets app_id
     *
     * @param string|null $app_id Deprecated but necessary for backward compatibility
     *
     * @return self
     */
    public function setAppId($app_id)
    {
        if (is_null($app_id)) {
            throw new \InvalidArgumentException('non-nullable app_id cannot be null');
        }
        $this->container['app_id'] = $app_id;

        return $this;
    }

    /**
     * Gets delivery_mode
     *
     * @return \Convoy\Client\Model\DatastoreDeliveryMode|null
     */
    public function getDeliveryMode()
    {
        return $this->container['delivery_mode'];
    }

    /**
     * Sets delivery_mode
     *
     * @param \Convoy\Client\Model\DatastoreDeliveryMode|null $delivery_mode Delivery mode configuration
     *
     * @return self
     */
    public function setDeliveryMode($delivery_mode)
    {
        if (is_null($delivery_mode)) {
            throw new \InvalidArgumentException('non-nullable delivery_mode cannot be null');
        }
        $this->container['delivery_mode'] = $delivery_mode;

        return $this;
    }

    /**
     * Gets endpoint_id
     *
     * @return string|null
     */
    public function getEndpointId()
    {
        return $this->container['endpoint_id'];
    }

    /**
     * Sets endpoint_id
     *
     * @param string|null $endpoint_id Destination endpoint ID
     *
     * @return self
     */
    public function setEndpointId($endpoint_id)
    {
        if (is_null($endpoint_id)) {
            throw new \InvalidArgumentException('non-nullable endpoint_id cannot be null');
        }
        $this->container['endpoint_id'] = $endpoint_id;

        return $this;
    }

    /**
     * Gets filter_config
     *
     * @return \Convoy\Client\Model\ModelsFilterConfiguration|null
     */
    public function getFilterConfig()
    {
        return $this->container['filter_config'];
    }

    /**
     * Sets filter_config
     *
     * @param \Convoy\Client\Model\ModelsFilterConfiguration|null $filter_config Filter configuration
     *
     * @return self
     */
    public function setFilterConfig($filter_config)
    {
        if (is_null($filter_config)) {
            throw new \InvalidArgumentException('non-nullable filter_config cannot be null');
        }
        $this->container['filter_config'] = $filter_config;

        return $this;
    }

    /**
     * Gets function
     *
     * @return string|null
     */
    public function getFunction()
    {
        return $this->container['function'];
    }

    /**
     * Sets function
     *
     * @param string|null $function Convoy supports mutating your request payload using a js function. Use this field to specify a `transform` function for this purpose. See this[https://docs.getconvoy.io/product-manual/subscriptions#functions] for more
     *
     * @return self
     */
    public function setFunction($function)
    {
        if (is_null($function)) {
            throw new \InvalidArgumentException('non-nullable function cannot be null');
        }
        $this->container['function'] = $function;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Subscription Nme
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets rate_limit_config
     *
     * @return \Convoy\Client\Model\ModelsRateLimitConfiguration|null
     */
    public function getRateLimitConfig()
    {
        return $this->container['rate_limit_config'];
    }

    /**
     * Sets rate_limit_config
     *
     * @param \Convoy\Client\Model\ModelsRateLimitConfiguration|null $rate_limit_config Rate limit configuration
     *
     * @return self
     */
    public function setRateLimitConfig($rate_limit_config)
    {
        if (is_null($rate_limit_config)) {
            throw new \InvalidArgumentException('non-nullable rate_limit_config cannot be null');
        }
        $this->container['rate_limit_config'] = $rate_limit_config;

        return $this;
    }

    /**
     * Gets source_id
     *
     * @return string|null
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param string|null $source_id Source Id
     *
     * @return self
     */
    public function setSourceId($source_id)
    {
        if (is_null($source_id)) {
            throw new \InvalidArgumentException('non-nullable source_id cannot be null');
        }
        $this->container['source_id'] = $source_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


