<?php
/**
 * ModelsAmqpPubSubconfig
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Convoy API Reference
 *
 * Convoy is a fast and secure webhooks proxy. This document contains datastore's API specification.
 *
 * The version of the OpenAPI document: 26.3.5
 * Contact: support@getconvoy.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Convoy\Client\Model;

use \ArrayAccess;
use \Convoy\Client\ObjectSerializer;

/**
 * ModelsAmqpPubSubconfig Class Doc Comment
 *
 * @category Class
 * @package  Convoy\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelsAmqpPubSubconfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'models.AmqpPubSubconfig';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'host' => 'string',
        'auth' => '\Convoy\Client\Model\ModelsAmqpAuth',
        'bind_exchange' => '\Convoy\Client\Model\ModelsAmqpExchange',
        'dead_letter_exchange' => 'string',
        'port' => 'string',
        'queue' => 'string',
        'schema' => 'string',
        'vhost' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'host' => null,
        'auth' => null,
        'bind_exchange' => null,
        'dead_letter_exchange' => null,
        'port' => null,
        'queue' => null,
        'schema' => null,
        'vhost' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'host' => false,
        'auth' => false,
        'bind_exchange' => false,
        'dead_letter_exchange' => false,
        'port' => false,
        'queue' => false,
        'schema' => false,
        'vhost' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'host' => 'host',
        'auth' => 'auth',
        'bind_exchange' => 'bindExchange',
        'dead_letter_exchange' => 'deadLetterExchange',
        'port' => 'port',
        'queue' => 'queue',
        'schema' => 'schema',
        'vhost' => 'vhost'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'host' => 'setHost',
        'auth' => 'setAuth',
        'bind_exchange' => 'setBindExchange',
        'dead_letter_exchange' => 'setDeadLetterExchange',
        'port' => 'setPort',
        'queue' => 'setQueue',
        'schema' => 'setSchema',
        'vhost' => 'setVhost'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'host' => 'getHost',
        'auth' => 'getAuth',
        'bind_exchange' => 'getBindExchange',
        'dead_letter_exchange' => 'getDeadLetterExchange',
        'port' => 'getPort',
        'queue' => 'getQueue',
        'schema' => 'getSchema',
        'vhost' => 'getVhost'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('auth', $data ?? [], null);
        $this->setIfExists('bind_exchange', $data ?? [], null);
        $this->setIfExists('dead_letter_exchange', $data ?? [], null);
        $this->setIfExists('port', $data ?? [], null);
        $this->setIfExists('queue', $data ?? [], null);
        $this->setIfExists('schema', $data ?? [], null);
        $this->setIfExists('vhost', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host host
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets auth
     *
     * @return \Convoy\Client\Model\ModelsAmqpAuth|null
     */
    public function getAuth()
    {
        return $this->container['auth'];
    }

    /**
     * Sets auth
     *
     * @param \Convoy\Client\Model\ModelsAmqpAuth|null $auth auth
     *
     * @return self
     */
    public function setAuth($auth)
    {
        if (is_null($auth)) {
            throw new \InvalidArgumentException('non-nullable auth cannot be null');
        }
        $this->container['auth'] = $auth;

        return $this;
    }

    /**
     * Gets bind_exchange
     *
     * @return \Convoy\Client\Model\ModelsAmqpExchange|null
     */
    public function getBindExchange()
    {
        return $this->container['bind_exchange'];
    }

    /**
     * Sets bind_exchange
     *
     * @param \Convoy\Client\Model\ModelsAmqpExchange|null $bind_exchange bind_exchange
     *
     * @return self
     */
    public function setBindExchange($bind_exchange)
    {
        if (is_null($bind_exchange)) {
            throw new \InvalidArgumentException('non-nullable bind_exchange cannot be null');
        }
        $this->container['bind_exchange'] = $bind_exchange;

        return $this;
    }

    /**
     * Gets dead_letter_exchange
     *
     * @return string|null
     */
    public function getDeadLetterExchange()
    {
        return $this->container['dead_letter_exchange'];
    }

    /**
     * Sets dead_letter_exchange
     *
     * @param string|null $dead_letter_exchange dead_letter_exchange
     *
     * @return self
     */
    public function setDeadLetterExchange($dead_letter_exchange)
    {
        if (is_null($dead_letter_exchange)) {
            throw new \InvalidArgumentException('non-nullable dead_letter_exchange cannot be null');
        }
        $this->container['dead_letter_exchange'] = $dead_letter_exchange;

        return $this;
    }

    /**
     * Gets port
     *
     * @return string|null
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param string|null $port port
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets queue
     *
     * @return string|null
     */
    public function getQueue()
    {
        return $this->container['queue'];
    }

    /**
     * Sets queue
     *
     * @param string|null $queue queue
     *
     * @return self
     */
    public function setQueue($queue)
    {
        if (is_null($queue)) {
            throw new \InvalidArgumentException('non-nullable queue cannot be null');
        }
        $this->container['queue'] = $queue;

        return $this;
    }

    /**
     * Gets schema
     *
     * @return string|null
     */
    public function getSchema()
    {
        return $this->container['schema'];
    }

    /**
     * Sets schema
     *
     * @param string|null $schema schema
     *
     * @return self
     */
    public function setSchema($schema)
    {
        if (is_null($schema)) {
            throw new \InvalidArgumentException('non-nullable schema cannot be null');
        }
        $this->container['schema'] = $schema;

        return $this;
    }

    /**
     * Gets vhost
     *
     * @return string|null
     */
    public function getVhost()
    {
        return $this->container['vhost'];
    }

    /**
     * Sets vhost
     *
     * @param string|null $vhost vhost
     *
     * @return self
     */
    public function setVhost($vhost)
    {
        if (is_null($vhost)) {
            throw new \InvalidArgumentException('non-nullable vhost cannot be null');
        }
        $this->container['vhost'] = $vhost;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


